### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectD_Group5#72]
Hi, we're having a call with F about the character page and wanted to know if you are providing any data visualization. if so what are you showing? can we see a sample?

**Comment by jcebel** [comment]
I understood there won't be a Data visualization provided by this project. We discussed that in the presentationweek with F.
They could choose and they chose to Do it by themself. They prefered that because it would be easier to have a unified style with this approach.. 
But maybe this Team Has ideas how to visualize the Data?

**Comment by kajo404** [comment]
@jonny3576 is correct. We discussed visualization with Team F during presentation week. We started experimenting with some graphs when first starting with the project but dropped it after talking to F.
