### ISSUE TITLE
[HELP] Pull Request

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectD_Group5#8]
Hello guys,

i can't create a pull request for the sentiment-analysis branch, why is that?

The pull requests thinks that files are in the develop branch that are actually not there? I am a bit confused...

**Comment by sacdallago** [comment]
Hi @kajo404 , is this the pull request you are referring to? https://github.com/Rostlab/JS16_ProjectD_Group5/pull/9

If that's the case, you have a conflict in your code w.r.t. develop. This is very normal, especially when the repo is at its initial stages. You need to merge develop into your branch, solve the conflicts, commit, push your branch again to origin, and then the pull request should update and allow you to merge.
You can have a look at the [presentation](https://github.com/Rostlab/JS16_ProjectD_Group5/files/158599/git.2.pdf) I made at the beginning, page 17. Otherwise [here](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow)

**Comment by kajo404** [comment]
Yes, I was able to make that pull request after i made changes to the sentiment-analysis branch. 

I just saw that Dat commited to the develop branch for some reason, do I need to do a reset again? I already reached out to Dat to clear things up.

Github wouldn't let me create the request because it saw no differences in develop and sentiment branch which is really odd because there clearly is a folder in the sentiment branch that is not on develop. 

Side question: what does w.r.t. stand for?

**Comment by sacdallago** [comment]
:) happy you solved this. Thanks for the heads up to Dat! You don't need to revert the commits at this stage, you have a lot on your head already, but yes: please also tell the other ones they should use the feature model ;)

Oh, and: with respect to ;)
